name: sipas
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  chat_bubbles: ^1.4.1
  flutter:
    sdk: flutter
  grouped_list: ^5.1.2
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash_screen.png"
  android_12:
    color: "#ffffff"
    image: "assets/images/splash_screen.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Robot
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
